# TCL File Generated by Component Editor on:
# Sun May 20 22:25:48 BST 2007
# DO NOT MODIFY

set_source_file "alt_jtagavalon.v"
set_module "alt_jtagavalon"
set_module_description ""
set_module_property instantiateInSystemModule true
set_module_property version "1.0"
set_module_property group "mr"
set_module_property editable true

# Module parameters
add_parameter "INSTANCE_ID" "integer" "0" ""
add_parameter "ADDR_WIDTH" "integer" "16" ""
add_parameter "DATA_WIDTH" "integer" "32" ""
add_parameter "MODE_WIDTH" "integer" "3" ""

# Clock Interface global_signals_clock
add_clock_interface "global_signals_clock"
set_interface_property "global_signals_clock" "externallyDriven" "false"
set_interface_property "global_signals_clock" "clockRateKnown" "false"
set_interface_property "global_signals_clock" "clockRate" "0"
# Ports in interface global_signals_clock
add_port_to_interface "global_signals_clock" "clk" "clk"
add_port_to_interface "global_signals_clock" "rst_n" "reset_n"

# Interface avalon_master_0
add_interface "avalon_master_0" "avalon" "master" "global_signals_clock"
set_interface_property "avalon_master_0" "interleaveBursts" "false"
set_interface_property "avalon_master_0" "burstOnBurstBoundariesOnly" "false"
set_interface_property "avalon_master_0" "doStreamReads" "false"
set_interface_property "avalon_master_0" "isBigEndian" "false"
set_interface_property "avalon_master_0" "isWriteable" "false"
set_interface_property "avalon_master_0" "isAsynchronous" "false"
set_interface_property "avalon_master_0" "registerOutgoingSignals" "false"
set_interface_property "avalon_master_0" "maxAddressWidth" "32"
set_interface_property "avalon_master_0" "registerIncomingSignals" "false"
set_interface_property "avalon_master_0" "dBSBigEndian" "false"
set_interface_property "avalon_master_0" "alwaysBurstMaxBurst" "false"
set_interface_property "avalon_master_0" "linewrapBursts" "false"
set_interface_property "avalon_master_0" "addressGroup" "0"
set_interface_property "avalon_master_0" "doStreamWrites" "false"
set_interface_property "avalon_master_0" "isReadable" "false"
# Ports in interface avalon_master_0
add_port_to_interface "avalon_master_0" "av_address" "address"
add_port_to_interface "avalon_master_0" "av_waitrequest" "waitrequest"
add_port_to_interface "avalon_master_0" "av_write_n" "write_n"
add_port_to_interface "avalon_master_0" "av_writedata" "writedata"
add_port_to_interface "avalon_master_0" "av_read_n" "read_n"
add_port_to_interface "avalon_master_0" "av_readdata" "readdata"
