# TCL File Generated by Component Editor 15.0
# Sun May 10 16:28:44 EDT 2015
# DO NOT MODIFY


# 
# cci_master "cci_master" v1.0
#  2015.05.10.16:28:44
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module cci_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME cci_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME cci_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cci_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cci_master.v VERILOG PATH cci_master/cci_master.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL cci_master
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file cci_master.v VERILOG PATH cci_master/cci_master.v


# 
# parameters
# 
add_parameter PEND_THRESH INTEGER 1
set_parameter_property PEND_THRESH DEFAULT_VALUE 1
set_parameter_property PEND_THRESH DISPLAY_NAME PEND_THRESH
set_parameter_property PEND_THRESH TYPE INTEGER
set_parameter_property PEND_THRESH UNITS None
set_parameter_property PEND_THRESH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PEND_THRESH HDL_PARAMETER true
add_parameter ADDR_LMT INTEGER 20
set_parameter_property ADDR_LMT DEFAULT_VALUE 20
set_parameter_property ADDR_LMT DISPLAY_NAME ADDR_LMT
set_parameter_property ADDR_LMT TYPE INTEGER
set_parameter_property ADDR_LMT UNITS None
set_parameter_property ADDR_LMT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_LMT HDL_PARAMETER true
add_parameter MDATA INTEGER 14
set_parameter_property MDATA DEFAULT_VALUE 14
set_parameter_property MDATA DISPLAY_NAME MDATA
set_parameter_property MDATA TYPE INTEGER
set_parameter_property MDATA UNITS None
set_parameter_property MDATA ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MDATA HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point cciconfig
# 
add_interface cciconfig avalon end
set_interface_property cciconfig addressUnits WORDS
set_interface_property cciconfig associatedClock clock
set_interface_property cciconfig associatedReset reset
set_interface_property cciconfig bitsPerSymbol 8
set_interface_property cciconfig burstOnBurstBoundariesOnly false
set_interface_property cciconfig burstcountUnits WORDS
set_interface_property cciconfig explicitAddressSpan 0
set_interface_property cciconfig holdTime 0
set_interface_property cciconfig linewrapBursts false
set_interface_property cciconfig maximumPendingReadTransactions 0
set_interface_property cciconfig maximumPendingWriteTransactions 0
set_interface_property cciconfig readLatency 0
set_interface_property cciconfig readWaitTime 1
set_interface_property cciconfig setupTime 0
set_interface_property cciconfig timingUnits Cycles
set_interface_property cciconfig writeWaitTime 0
set_interface_property cciconfig ENABLED true
set_interface_property cciconfig EXPORT_OF ""
set_interface_property cciconfig PORT_NAME_MAP ""
set_interface_property cciconfig CMSIS_SVD_VARIABLES ""
set_interface_property cciconfig SVD_ADDRESS_GROUP ""

add_interface_port cciconfig cciconfig_address address Input 32
add_interface_port cciconfig cciconfig_write write Input 1
add_interface_port cciconfig cciconfig_writedata writedata Input 32
add_interface_port cciconfig cciconfig_waitrequest waitrequest Output 1
set_interface_assignment cciconfig embeddedsw.configuration.isFlash 0
set_interface_assignment cciconfig embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment cciconfig embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cciconfig embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ccidata
# 
add_interface ccidata avalon start
set_interface_property ccidata addressUnits WORDS
set_interface_property ccidata associatedClock clock
set_interface_property ccidata associatedReset reset
set_interface_property ccidata bitsPerSymbol 8
set_interface_property ccidata burstOnBurstBoundariesOnly false
set_interface_property ccidata burstcountUnits WORDS
set_interface_property ccidata doStreamReads false
set_interface_property ccidata doStreamWrites false
set_interface_property ccidata holdTime 0
set_interface_property ccidata linewrapBursts false
set_interface_property ccidata maximumPendingReadTransactions 0
set_interface_property ccidata maximumPendingWriteTransactions 0
set_interface_property ccidata readLatency 0
set_interface_property ccidata readWaitTime 1
set_interface_property ccidata setupTime 0
set_interface_property ccidata timingUnits Cycles
set_interface_property ccidata writeWaitTime 0
set_interface_property ccidata ENABLED true
set_interface_property ccidata EXPORT_OF ""
set_interface_property ccidata PORT_NAME_MAP ""
set_interface_property ccidata CMSIS_SVD_VARIABLES ""
set_interface_property ccidata SVD_ADDRESS_GROUP ""

add_interface_port ccidata ccidata_address address Output 58
add_interface_port ccidata ccidata_byteenable byteenable Output 64
add_interface_port ccidata ccidata_write write Output 1
add_interface_port ccidata ccidata_writedata writedata Output 512
add_interface_port ccidata ccidata_read read Output 1
add_interface_port ccidata ccidata_readdata readdata Input 512
add_interface_port ccidata ccidata_readdatavalid readdatavalid Input 1
add_interface_port ccidata ccidata_waitrequest waitrequest Input 1


# 
# connection point kernel
# 
add_interface kernel avalon start
set_interface_property kernel addressUnits WORDS
set_interface_property kernel associatedClock clock
set_interface_property kernel associatedReset reset
set_interface_property kernel bitsPerSymbol 8
set_interface_property kernel burstOnBurstBoundariesOnly false
set_interface_property kernel burstcountUnits WORDS
set_interface_property kernel doStreamReads false
set_interface_property kernel doStreamWrites false
set_interface_property kernel holdTime 0
set_interface_property kernel linewrapBursts false
set_interface_property kernel maximumPendingReadTransactions 0
set_interface_property kernel maximumPendingWriteTransactions 0
set_interface_property kernel readLatency 0
set_interface_property kernel readWaitTime 1
set_interface_property kernel setupTime 0
set_interface_property kernel timingUnits Cycles
set_interface_property kernel writeWaitTime 0
set_interface_property kernel ENABLED true
set_interface_property kernel EXPORT_OF ""
set_interface_property kernel PORT_NAME_MAP ""
set_interface_property kernel CMSIS_SVD_VARIABLES ""
set_interface_property kernel SVD_ADDRESS_GROUP ""

add_interface_port kernel kernel_write write Output 1
add_interface_port kernel kernel_read read Output 1
add_interface_port kernel kernel_writedata writedata Output 32
add_interface_port kernel kernel_readdata readdata Input 32
add_interface_port kernel kernel_readdatavalid readdatavalid Input 1
add_interface_port kernel kernel_waitrequest waitrequest Input 1
add_interface_port kernel kernel_address address Output 36


# 
# connection point dsm_base
# 
add_interface dsm_base conduit end
set_interface_property dsm_base associatedClock ""
set_interface_property dsm_base associatedReset ""
set_interface_property dsm_base ENABLED true
set_interface_property dsm_base EXPORT_OF ""
set_interface_property dsm_base PORT_NAME_MAP ""
set_interface_property dsm_base CMSIS_SVD_VARIABLES ""
set_interface_property dsm_base SVD_ADDRESS_GROUP ""

add_interface_port dsm_base dsm_base dsm_base Input 64

