#!/bin/bash

echo $1
echo $2


filename=$(basename "$2")
extension="${filename##*.}"

fpga_bin_path=$2

if [ "$extension" == "aocx" ]; then
	fpga_bin_path="fpga.bin"
	aocl binedit $2 get .acl.fpga.bin $fpga_bin_path
fi

echo $fpga_bin_path

if [ "$OPENCL_ASE_SIM" == "1" ]; then
	#simulation programming flow(start VCS)
	if [[ "$1" != "acl0" ]] ; then
		echo "Not acl0, exiting without launching vcs"
		exit 0
	fi                                                                                     
	
	#uncompress and prepare modelsim files
	mkdir -p temp_simulation
	cd temp_simulation
	tar zxvf ../$fpga_bin_path
	export KDIR=$PWD
	
	rm -fr ./ase
	cp -r $ASE_SRC_PATH ./ase
	cp -rf $AOCL_BOARD_PACKAGE_ROOT/ase/patch/* ./ase
	cd ase
	
	mkdir dummy_rtl_dir
	touch dummy_rtl_dir/dummy_rtl_file.sv
	mkdir dummy_vhd_dir
	touch dummy_vhd_dir/dummy_vhd_file.vhd
	
	set -e
	#needed because ase now requires afu_platform_config script in the exe
	#search path
	export PATH=${OPAE_INSTALL_PATH}/bin:${PATH}
	python ./scripts/generate_ase_environment.py -p discrete dummy_rtl_dir dummy_vhd_dir
	
	echo >> ase_sources.mk
	echo "ASE_DISCRETE_EMIF_MODEL=EMIF_MODEL_BASIC" >> ase_sources.mk
	#echo "ASE_DISCRETE_EMIF_MODEL=EMIF_MODEL_ADVANCED" >> ase_sources.mk
	echo >> ase_sources.mk
	
	bash run_sim.sh

else
	echo "ERROR: HW configuration is not supported with this script"
	exit 1
fi

