#!/bin/bash
#script to set up common variables

#get exact script path
COMMON_SCRIPT_PATH=`readlink -f ${BASH_SOURCE[0]}`
#get director of script path
COMMON_SCRIPT_DIR_PATH="$(dirname $COMMON_SCRIPT_PATH)"
export ROOT_PROJECT_PATH="$(dirname $COMMON_SCRIPT_DIR_PATH)"

BUILD_DIR=$ROOT_PROJECT_PATH/build
FPGA_API_SRC_PATH=$BUILD_DIR/fpga_api_src
FPGA_API_INST_PATH=$BUILD_DIR/fpga_api_inst
FPGA_API_BUILD_PATH=$BUILD_DIR/fpga_api_build
PACKAGE_DIR_PATH=$ROOT_PROJECT_PATH/packages

if [ "$FPGA_API_PATH" == "" ]; then
	export FPGA_API_PATH=$FPGA_API_INST_PATH
fi
export AOCL_BOARD_PACKAGE_ROOT=$ROOT_PROJECT_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ALTERAOCLSDKROOT/host/linux64/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$AOCL_BOARD_PACKAGE_ROOT/host/linux64/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$FPGA_API_PATH/lib
export CL_CONTEXT_COMPILER_MODE_ALTERA=3
export QUARTUS_HOME=$QUARTUS_ROOTDIR
export ASE_WORKDIR=./temp_simulation/ase/work/
export MPF_INSTALL_PATH=$BUILD_DIR/mpf
export ASE_SRC_PATH=$FPGA_API_SRC_PATH/ase
export ACDS_ARC_RESOURCES="acl/17.0,acds/17.0,qedition/pro"
